In [1]:
import pandas as pd

# Load dataset
df = pd.read_csv('ecommerce-session-bigquery.csv')

In [123]:
# Melihat dimensi dataset
print("Shape of the dataset:", df.shape)

# Menampilkan 5 baris pertama dataset
print(df.head())

Shape of the dataset: (10000, 32)
         fullVisitorId channelGrouping     time        country  \
0  2515546493837534633  Organic Search   966564         Taiwan
1  9361741997835388618  Organic Search   157377         France
2  7313828956068851679        Referral   228279  United States
3  6036794406403793540  Organic Search  1615618  United States
4  7847280609739507227  Organic Search    37832         Canada

                            city  totalTransactionRevenue  transactions  \
0                      (not set)                      NaN           NaN
1  not available in demo dataset                      NaN           NaN
2                  San Francisco                      NaN           NaN
3                        Boulder                      NaN           NaN
4  not available in demo dataset                      NaN           NaN

   timeOnSite  pageviews  sessionQualityDim      date     visitId  type  \
0      1567.0       82.0               17.0  20170721  1500643403  PAGE
1       321.0        8.0                NaN  20170413  1492114470  PAGE
2       927.0       11.0               63.0  20170727  1501198444  PAGE
3      1616.0       13.0               38.0  20170731  1501522359  PAGE
4      1222.0       45.0               53.0  20170728  1501300311  PAGE

   productRefundAmount  productQuantity  productPrice  productRevenue  \
0                  NaN              NaN             0             NaN
1                  NaN              NaN             0             NaN
2                  NaN              NaN             0             NaN
3                  NaN              NaN             0             NaN
4                  NaN              NaN             0             NaN

  productSKU                       v2ProductName v2ProductCategory  \
0    9180781            Suitcase Organizer Cubes         (not set)
1    9180793  26 oz Double Wall Insulated Bottle         (not set)
2    9180838            Metal Texture Roller Pen         (not set)
3    9180838            Metal Texture Roller Pen         (not set)
4    9180838            Metal Texture Roller Pen         (not set)

  productVariant currencyCode  itemQuantity  itemRevenue  transactionRevenue  \
0      (not set)          USD           NaN          NaN                 NaN
1      (not set)          USD           NaN          NaN                 NaN
2      (not set)          USD           NaN          NaN                 NaN
3      (not set)          USD           NaN          NaN                 NaN
4      (not set)          USD           NaN          NaN                 NaN

   transactionId pageTitle  searchKeyword   pagePathLevel1  \
0            NaN       NaN            NaN  /storeitem.html
1            NaN       NaN            NaN  /storeitem.html
2            NaN       NaN            NaN  /storeitem.html
3            NaN       NaN            NaN  /storeitem.html
4            NaN       NaN            NaN  /storeitem.html

   eCommerceAction_type  eCommerceAction_step  eCommerceAction_option
0                     0                     1                     NaN
1                     0                     1                     NaN
2                     0                     1                     NaN
3                     0                     1                     NaN
4                     0                     1                     NaN

In [124]:
# Informasi tentang dataset
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   fullVisitorId            10000 non-null  uint64
 1   channelGrouping          10000 non-null  object
 2   time                     10000 non-null  int64
 3   country                  10000 non-null  object
 4   city                     10000 non-null  object
 5   totalTransactionRevenue  619 non-null    float64
 6   transactions             628 non-null    float64
 7   timeOnSite               9713 non-null   float64
 8   pageviews                9999 non-null   float64
 9   sessionQualityDim        19 non-null     float64
 10  date                     10000 non-null  int64
 11  visitId                  10000 non-null  int64
 12  type                     10000 non-null  object
 13  productRefundAmount      0 non-null      float64
 14  productQuantity          45 non-null     float64
 15  productPrice             10000 non-null  int64
 16  productRevenue           0 non-null      float64
 17  productSKU               10000 non-null  object
 18  v2ProductName            10000 non-null  object
 19  v2ProductCategory        10000 non-null  object
 20  productVariant           10000 non-null  object
 21  currencyCode             9614 non-null   object
 22  itemQuantity             0 non-null      float64
 23  itemRevenue              0 non-null      float64
 24  transactionRevenue       0 non-null      float64
 25  transactionId            0 non-null      float64
 26  pageTitle                9908 non-null   object
 27  searchKeyword            0 non-null      float64
 28  pagePathLevel1           10000 non-null  object
 29  eCommerceAction_type     10000 non-null  int64
 30  eCommerceAction_step     10000 non-null  int64
 31  eCommerceAction_option   0 non-null      float64
dtypes: float64(14), int64(6), object(11), uint64(1)
memory usage: 2.4+ MB
None

In [125]:
# Statistik deskriptif
print(df.describe())

       fullVisitorId          time  totalTransactionRevenue  transactions  \
count   1.000000e+04  1.000000e+04             6.190000e+02    628.000000
mean    4.538050e+18  3.248462e+05             2.103635e+08      1.050955
std     3.038982e+18  5.647221e+05             5.656026e+08      0.289005
min     1.664653e+14  0.000000e+00             3.530000e+06      1.000000
25%     1.701094e+18  4.252400e+04             5.508000e+07      1.000000
50%     4.449181e+18  1.357180e+05             9.542000e+07      1.000000
75%     7.170959e+18  3.542545e+05             1.866600e+08      1.000000
max     9.994767e+18  1.089403e+07             6.831960e+09      6.000000

         timeOnSite    pageviews  sessionQualityDim          date  \
count   9713.000000  9999.000000          19.000000  1.000000e+04
mean     720.119222    22.142114          50.210526  2.016097e+07
std      967.997653    26.631372          32.481754  9.067598e+02
min        1.000000     1.000000           1.000000  2.016080e+07
25%      164.000000     7.000000          19.500000  2.016082e+07
50%      383.000000    14.000000          62.000000  2.016090e+07
75%      898.000000    27.000000          79.000000  2.016092e+07
max    15020.000000   429.000000          92.000000  2.017080e+07

            visitId  productRefundAmount  productQuantity  productPrice  \
count  1.000000e+04                  0.0        45.000000  1.000000e+04
mean   1.473169e+09                  NaN         3.444444  1.585565e+07
std    2.518655e+06                  NaN         6.468650  2.095339e+07
min    1.470036e+09                  NaN         1.000000  0.000000e+00
25%    1.471555e+09                  NaN         1.000000  4.990000e+06
50%    1.473019e+09                  NaN         1.000000  9.990000e+06
75%    1.474471e+09                  NaN         2.000000  1.599000e+07
max    1.501622e+09                  NaN        32.000000  9.999000e+07

       productRevenue  itemQuantity  itemRevenue  transactionRevenue  \
count             0.0           0.0          0.0                 0.0
mean              NaN           NaN          NaN                 NaN
std               NaN           NaN          NaN                 NaN
min               NaN           NaN          NaN                 NaN
25%               NaN           NaN          NaN                 NaN
50%               NaN           NaN          NaN                 NaN
75%               NaN           NaN          NaN                 NaN
max               NaN           NaN          NaN                 NaN

       transactionId  searchKeyword  eCommerceAction_type  \
count            0.0            0.0          10000.000000
mean             NaN            NaN              0.071500
std              NaN            NaN              0.363595
min              NaN            NaN              0.000000
25%              NaN            NaN              0.000000
50%              NaN            NaN              0.000000
75%              NaN            NaN              0.000000
max              NaN            NaN              3.000000

       eCommerceAction_step  eCommerceAction_option
count               10000.0                     0.0
mean                    1.0                     NaN
std                     0.0                     NaN
min                     1.0                     NaN
25%                     1.0                     NaN
50%                     1.0                     NaN
75%                     1.0                     NaN
max                     1.0                     NaN

In [9]:
import pandas as pd

# Load the dataset
data = pd.read_csv('ecommerce-session-bigquery.csv')

# Display the first few rows of the dataset
print(data.head())

         fullVisitorId channelGrouping     time        country  \
0  2515546493837534633  Organic Search   966564         Taiwan
1  9361741997835388618  Organic Search   157377         France
2  7313828956068851679        Referral   228279  United States
3  6036794406403793540  Organic Search  1615618  United States
4  7847280609739507227  Organic Search    37832         Canada

                            city  totalTransactionRevenue  transactions  \
0                      (not set)                      NaN           NaN
1  not available in demo dataset                      NaN           NaN
2                  San Francisco                      NaN           NaN
3                        Boulder                      NaN           NaN
4  not available in demo dataset                      NaN           NaN

   timeOnSite  pageviews  sessionQualityDim  ...  itemQuantity  itemRevenue  \
0      1567.0       82.0               17.0  ...           NaN          NaN
1       321.0        8.0                NaN  ...           NaN          NaN
2       927.0       11.0               63.0  ...           NaN          NaN
3      1616.0       13.0               38.0  ...           NaN          NaN
4      1222.0       45.0               53.0  ...           NaN          NaN

  transactionRevenue  transactionId  pageTitle  searchKeyword  \
0                NaN            NaN        NaN            NaN
1                NaN            NaN        NaN            NaN
2                NaN            NaN        NaN            NaN
3                NaN            NaN        NaN            NaN
4                NaN            NaN        NaN            NaN

    pagePathLevel1 eCommerceAction_type eCommerceAction_step  \
0  /storeitem.html                    0                    1
1  /storeitem.html                    0                    1
2  /storeitem.html                    0                    1
3  /storeitem.html                    0                    1
4  /storeitem.html                    0                    1

  eCommerceAction_option
0                    NaN
1                    NaN
2                    NaN
3                    NaN
4                    NaN

[5 rows x 32 columns]

In [38]:
# Import libraries
import pandas as pd

# Load dataset from CSV file
dataset_path = 'ecommerce-session-bigquery.csv'
df = pd.read_csv(dataset_path)

# Convert 'date' column to datetime format
df['date'] = pd.to_datetime(df['date'])

# Set the option to display all columns
pd.set_option('display.max_columns', None)

# Display the DataFrame as a table
display(df.head(20))

,fullVisitorId,channelGrouping,time,country,city,totalTransactionRevenue,transactions,timeOnSite,pageviews,sessionQualityDim,date,visitId,type,productRefundAmount,productQuantity,productPrice,productRevenue,productSKU,v2ProductName,v2ProductCategory,productVariant,currencyCode,itemQuantity,itemRevenue,transactionRevenue,transactionId,pageTitle,searchKeyword,pagePathLevel1,eCommerceAction_type,eCommerceAction_step,eCommerceAction_option
0,2515546493837534633,Organic Search,966564,Taiwan,(not set),NaN,NaN,1567.0,82.0,17.0,1970-01-01 00:00:00.020170721,1500643403,PAGE,NaN,NaN,0,NaN,9180781,Suitcase Organizer Cubes,(not set),(not set),USD,NaN,NaN,NaN,NaN,NaN,NaN,/storeitem.html,0,1,NaN
1,9361741997835388618,Organic Search,157377,France,not available in demo dataset,NaN,NaN,321.0,8.0,NaN,1970-01-01 00:00:00.020170413,1492114470,PAGE,NaN,NaN,0,NaN,9180793,26 oz Double Wall Insulated Bottle,(not set),(not set),USD,NaN,NaN,NaN,NaN,NaN,NaN,/storeitem.html,0,1,NaN
2,7313828956068851679,Referral,228279,United States,San Francisco,NaN,NaN,927.0,11.0,63.0,1970-01-01 00:00:00.020170727,1501198444,PAGE,NaN,NaN,0,NaN,9180838,Metal Texture Roller Pen,(not set),(not set),USD,NaN,NaN,NaN,NaN,NaN,NaN,/storeitem.html,0,1,NaN
3,6036794406403793540,Organic Search,1615618,United States,Boulder,NaN,NaN,1616.0,13.0,38.0,1970-01-01 00:00:00.020170731,1501522359,PAGE,NaN,NaN,0,NaN,9180838,Metal Texture Roller Pen,(not set),(not set),USD,NaN,NaN,NaN,NaN,NaN,NaN,/storeitem.html,0,1,NaN
4,7847280609739507227,Organic Search,37832,Canada,not available in demo dataset,NaN,NaN,1222.0,45.0,53.0,1970-01-01 00:00:00.020170728,1501300311,PAGE,NaN,NaN,0,NaN,9180838,Metal Texture Roller Pen,(not set),(not set),USD,NaN,NaN,NaN,NaN,NaN,NaN,/storeitem.html,0,1,NaN
5,1371078687799372953,Referral,478901,United States,Ann Arbor,67570000.0,1.0,1569.0,48.0,87.0,1970-01-01 00:00:00.020170726,1501111386,PAGE,NaN,NaN,0,NaN,9180838,Metal Texture Roller Pen,(not set),(not set),USD,NaN,NaN,NaN,NaN,NaN,NaN,/storeitem.html,0,1,NaN
6,8781227467221587011,Referral,119567,United States,Mountain View,24710000.0,1.0,1007.0,35.0,71.0,1970-01-01 00:00:00.020170727,1501203918,PAGE,NaN,NaN,0,NaN,9180838,Metal Texture Roller Pen,(not set),(not set),USD,NaN,NaN,NaN,NaN,NaN,NaN,/storeitem.html,0,1,NaN
7,7328657227470299189,Organic Search,1115991,India,not available in demo dataset,NaN,NaN,3326.0,41.0,NaN,1970-01-01 00:00:00.020170305,1488700723,PAGE,NaN,NaN,0,NaN,9180842,Maze Pen,(not set),(not set),USD,NaN,NaN,NaN,NaN,NaN,NaN,/storeitem.html,0,1,NaN
8,603507101721972238,Referral,63158,United States,not available in demo dataset,NaN,NaN,372.0,20.0,NaN,1970-01-01 00:00:00.020170323,1490286223,PAGE,NaN,NaN,0,NaN,9180844,Gunmetal Roller Ball Pen,(not set),(not set),USD,NaN,NaN,NaN,NaN,NaN,NaN,/storeitem.html,0,1,NaN
9,2410100047658323318,Direct,487916,New Zealand,not available in demo dataset,NaN,NaN,488.0,6.0,NaN,1970-01-01 00:00:00.020170306,1488836135,PAGE,NaN,NaN,0,NaN,9180844,Gunmetal Roller Ball Pen,(not set),(not set),USD,NaN,NaN,NaN,NaN,NaN,NaN,/storeitem.html,0,1,NaN
10,7328657227470299189,Organic Search,1115991,India,not available in demo dataset,NaN,NaN,3326.0,41.0,NaN,1970-01-01 00:00:00.020170305,1488700723,PAGE,NaN,NaN,0,NaN,9180844,Gunmetal Roller Ball Pen,(not set),(not set),USD,NaN,NaN,NaN,NaN,NaN,NaN,/storeitem.html,0,1,NaN
11,6359403243542167475,Organic Search,161016,United States,not available in demo dataset,NaN,NaN,404.0,24.0,NaN,1970-01-01 00:00:00.020170215,1487203514,PAGE,NaN,NaN,0,NaN,9181019,Google Tri-blend Hoodie Grey,(not set),(not set),USD,NaN,NaN,NaN,NaN,NaN,NaN,/storeitem.html,0,1,NaN
12,4563918079034331605,Organic Search,1165111,Italy,not available in demo dataset,NaN,NaN,1266.0,27.0,NaN,1970-01-01 00:00:00.020170215,1487175528,PAGE,NaN,NaN,0,NaN,9181019,Google Tri-blend Hoodie Grey,(not set),(not set),USD,NaN,NaN,NaN,NaN,NaN,NaN,/storeitem.html,0,1,NaN
13,3502451034522748027,Organic Search,260638,United States,not available in demo dataset,NaN,NaN,377.0,12.0,NaN,1970-01-01 00:00:00.020170125,1485392662,PAGE,NaN,NaN,0,NaN,9181573,Google Snapback Hat Black,(not set),(not set),USD,NaN,NaN,NaN,NaN,NaN,NaN,/storeitem.html,0,1,NaN
14,6254574407334719565,Organic Search,59946,Denmark,not available in demo dataset,NaN,NaN,343.0,15.0,NaN,1970-01-01 00:00:00.020170126,1485481041,PAGE,NaN,NaN,0,NaN,9181573,Google Snapback Hat Black,(not set),(not set),USD,NaN,NaN,NaN,NaN,NaN,NaN,/storeitem.html,0,1,NaN
15,1419842828452102862,Organic Search,766951,United States,Mountain View,NaN,NaN,1792.0,72.0,62.0,1970-01-01 00:00:00.020170801,1501605330,PAGE,NaN,NaN,0,NaN,9181573,Google Snapback Hat Black,(not set),(not set),USD,NaN,NaN,NaN,NaN,NaN,NaN,/storeitem.html,0,1,NaN
16,9893914155363716533,Referral,205156,United States,Los Angeles,NaN,NaN,426.0,20.0,85.0,1970-01-01 00:00:00.020170801,1501621677,PAGE,NaN,NaN,0,NaN,9181573,Google Snapback Hat Black,(not set),(not set),USD,NaN,NaN,NaN,NaN,NaN,NaN,/storeitem.html,0,1,NaN
17,8401606893927168081,Organic Search,563230,United States,not available in demo dataset,NaN,NaN,992.0,23.0,NaN,1970-01-01 00:00:00.020170403,1491256189,PAGE,NaN,NaN,0,NaN,9181664,Waterproof Gear Bag,(not set),(not set),USD,NaN,NaN,NaN,NaN,NaN,NaN,/storeitem.html,0,1,NaN
18,997271511212133268,Referral,180572,United States,Mountain View,NaN,NaN,743.0,19.0,NaN,1970-01-01 00:00:00.020170404,1491347644,PAGE,NaN,NaN,0,NaN,9181664,Waterproof Gear Bag,(not set),(not set),USD,NaN,NaN,NaN,NaN,NaN,NaN,/storeitem.html,0,1,NaN
19,7932128536242606019,Organic Search,952790,United States,not available in demo dataset,NaN,NaN,1763.0,36.0,NaN,1970-01-01 00:00:00.020170424,1493057283,PAGE,NaN,NaN,0,NaN,9181664,Waterproof Gear Bag,(not set),(not set),USD,NaN,NaN,NaN,NaN,NaN,NaN,/storeitem.html,0,1,NaN

In [31]:
df_not_null_revenue = df[df['totalTransactionRevenue'].notnull()]

# Display the filtered DataFrame
print("Data where transactionRevenue is not null:")
print(df_not_null_revenue)

Data where transactionRevenue is not null:
            fullVisitorId channelGrouping                          time  \
5     1371078687799372953        Referral 1970-01-01 00:00:00.000478901
6     8781227467221587011        Referral 1970-01-01 00:00:00.000119567
21    5024679608681889824  Organic Search 1970-01-01 00:00:00.003155627
32    7382833428985431536        Referral 1970-01-01 00:00:00.000812138
48    7199611745811583535        Referral 1970-01-01 00:00:00.000095056
...                   ...             ...                           ...
9879  4825534357105727679        Referral 1970-01-01 00:00:00.000017118
9925  7166253532069552655         Display 1970-01-01 00:00:00.000279254
9938  5262771322194198136        Referral 1970-01-01 00:00:00.000005581
9958  4835031132385744572          Direct 1970-01-01 00:00:00.001259955
9968  2518447979646501002  Organic Search 1970-01-01 00:00:00.000121173

            country           city  totalTransactionRevenue  transactions  \
5     United States      Ann Arbor               67570000.0           1.0
6     United States  Mountain View               24710000.0           1.0
21    United States        Houston              123390000.0           1.0
32    United States        Chicago              122390000.0           1.0
48    United States        Boulder              467600000.0           1.0
...             ...            ...                      ...           ...
9879  United States  Mountain View              125100000.0           1.0
9925  United States  San Francisco              451700000.0           1.0
9938  United States         Austin              150340000.0           1.0
9958  United States      Palo Alto               62870000.0           1.0
9968  United States       New York               78150000.0           1.0

      timeOnSite  pageviews  sessionQualityDim      date     visitId  type  \
5         1569.0       48.0               87.0  20170726  1501111386  PAGE
6         1007.0       35.0               71.0  20170727  1501203918  PAGE
21        3899.0       54.0               80.0  20170715  1500148319  PAGE
32        1296.0       31.0                NaN  20170416  1492363119  PAGE
48         710.0       27.0                NaN  20170104  1483554305  PAGE
...          ...        ...                ...       ...         ...   ...
9879       356.0       14.0                NaN  20160809  1470762213  PAGE
9925      1187.0       41.0                NaN  20160818  1471550764  PAGE
9938      1731.0       61.0                NaN  20160822  1471906107  PAGE
9958      1643.0       32.0                NaN  20160805  1470409970  PAGE
9968       705.0       40.0                NaN  20160820  1471740007  PAGE

      productRefundAmount  productQuantity  productPrice  productRevenue  \
5                     NaN              NaN             0             NaN
6                     NaN              NaN             0             NaN
21                    NaN              NaN             0             NaN
32                    NaN              NaN             0             NaN
48                    NaN              NaN             0             NaN
...                   ...              ...           ...             ...
9879                  NaN              NaN       4990000             NaN
9925                  NaN              NaN       4990000             NaN
9938                  NaN              NaN       4990000             NaN
9958                  NaN              NaN       4990000             NaN
9968                  NaN              NaN       4990000             NaN

          productSKU                                      v2ProductName  \
5            9180838                           Metal Texture Roller Pen
6            9180838                           Metal Texture Roller Pen
21           9182569                           Google Men's  Zip Hoodie
32           9182721  Google Men's 100% Cotton Short Sleeve Hero Tee...
48           9182761                   Google Women's Yoga Jacket Black
...              ...                                                ...
9879  GGOEGBMJ013399                                          Sport Bag
9925  GGOEGBMJ013399                                          Sport Bag
9938  GGOEGBMJ013399                                          Sport Bag
9958  GGOEGBMJ013399                                          Sport Bag
9968  GGOEGBMJ013399                                          Sport Bag

              v2ProductCategory productVariant currencyCode  itemQuantity  \
5                     (not set)      (not set)          USD           NaN
6                     (not set)      (not set)          USD           NaN
21                    (not set)      (not set)          USD           NaN
32                    (not set)      (not set)          USD           NaN
48                    (not set)      (not set)          USD           NaN
...                         ...            ...          ...           ...
9879  Home/Limited Supply/Bags/      (not set)          USD           NaN
9925  Home/Limited Supply/Bags/      (not set)          USD           NaN
9938                 Home/Bags/      (not set)          USD           NaN
9958  Home/Limited Supply/Bags/      (not set)          NaN           NaN
9968                 Home/Bags/      (not set)          USD           NaN

      itemRevenue  transactionRevenue  transactionId pageTitle  searchKeyword  \
5             NaN                 NaN            NaN       NaN            NaN
6             NaN                 NaN            NaN       NaN            NaN
21            NaN                 NaN            NaN       NaN            NaN
32            NaN                 NaN            NaN       NaN            NaN
48            NaN                 NaN            NaN       NaN            NaN
...           ...                 ...            ...       ...            ...
9879          NaN                 NaN            NaN      Bags            NaN
9925          NaN                 NaN            NaN      Bags            NaN
9938          NaN                 NaN            NaN      Bags            NaN
9958          NaN                 NaN            NaN      Bags            NaN
9968          NaN                 NaN            NaN      Bags            NaN

         pagePathLevel1  eCommerceAction_type  eCommerceAction_step  \
5       /storeitem.html                     0                     1
6       /storeitem.html                     0                     1
21      /storeitem.html                     0                     1
32      /storeitem.html                     0                     1
48      /storeitem.html                     0                     1
...                 ...                   ...                   ...
9879  /google+redesign/                     0                     1
9925  /google+redesign/                     0                     1
9938  /google+redesign/                     0                     1
9958  /google+redesign/                     2                     1
9968  /google+redesign/                     0                     1

      eCommerceAction_option
5                        NaN
6                        NaN
21                       NaN
32                       NaN
48                       NaN
...                      ...
9879                     NaN
9925                     NaN
9938                     NaN
9958                     NaN
9968                     NaN

[619 rows x 32 columns]

### Identify top products based on the total transaction revenue per day.

In [ ]:
# Membuat kondisi boolean untuk memeriksa totalTransactionRevenue > 0
revenue_greater_than_zero = df['totalTransactionRevenue'] > 0

# Menggunakan kondisi boolean untuk memfilter baris DataFrame
revenue_positive_df = df[revenue_greater_than_zero]

# Mengurutkan DataFrame berdasarkan totalTransactionRevenue secara menurun
revenue_positive_sorted = revenue_positive_df.sort_values(by='totalTransactionRevenue', ascending=False)

# Menampilkan DataFrame yang totalTransactionRevenue > 0 yang sudah diurutkan
display(revenue_positive_sorted.head(100))

In [51]:
# Import libraries
import pandas as pd
from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import LabelEncoder

# Load dataset from CSV file
dataset_path = 'ecommerce-session-bigquery.csv'
df = pd.read_csv(dataset_path)

# Convert 'date' column to datetime format
df['time'] = pd.to_datetime(df['time'], unit='s')

# Scenario 1: Identify top products based on the total transaction revenue per day
daily_revenue = df.groupby(['time', 'v2ProductName'])['totalTransactionRevenue'].sum().reset_index()
top_products_per_day = daily_revenue.groupby('time').apply(lambda x: x.nlargest(100, 'totalTransactionRevenue')).reset_index(drop=True)

print("Top products based on total transaction revenue per day:")

# Set the option to display all columns
pd.set_option('display.max_columns', None)

# Display the DataFrame as a table
display(top_products_per_day.head(50))

Top products based on total transaction revenue per day:

,time,v2ProductName,totalTransactionRevenue
0,1970-01-01 00:00:00,Google Lunch Bag,215000000.0
1,1970-01-01 00:00:00,Google Canvas Tote Natural/Navy,215000000.0
2,1970-01-01 00:00:00,Waterproof Gear Bag,145310000.0
3,1970-01-01 00:00:00,Google Tote Bag,145100000.0
4,1970-01-01 00:00:00,Google Zipper-front Sports Bag,118490000.0
5,1970-01-01 00:00:00,Straw Beach Mat,62890000.0
6,1970-01-01 00:00:00,Speed Zone Air Mesh Tote,0.0
7,1970-01-01 00:00:00,Latitudes Foldaway Shopper,0.0
8,1970-01-01 00:00:00,Reusable Shopping Bag,0.0
9,1970-01-01 00:00:00,SPF-15 Lip Balm,0.0
10,1970-01-01 00:00:00,SPF-15 Slim & Slender Lip Balm,0.0
11,1970-01-01 00:00:00,Seat Pack Organizer,0.0
12,1970-01-01 00:00:00,Sport Bag,0.0
13,1970-01-01 00:00:00,Koozie Can Kooler,0.0
14,1970-01-01 00:00:00,Suitcase Organizer Cubes,0.0
15,1970-01-01 00:00:00,Switch Tone Color Crayon Pen,0.0
16,1970-01-01 00:00:00,Waterpoof Gear Bag,0.0
17,1970-01-01 00:00:00,Windup Android,0.0
18,1970-01-01 00:00:00,Yoga Mat,0.0
19,1970-01-01 00:00:00,YouTube Custom Decals,0.0
20,1970-01-01 00:00:00,Large Zipper Top Tote Bag,0.0
21,1970-01-01 00:00:00,1 oz Hand Sanitizer,0.0
22,1970-01-01 00:00:00,Kick Ball,0.0
23,1970-01-01 00:00:00,8 pc Android Sticker Sheet,0.0
24,1970-01-01 00:00:00,Android Sticker Sheet Ultra Removable,0.0
25,1970-01-01 00:00:00,Bottle Opener Clip,0.0
26,1970-01-01 00:00:00,Chevron Shopper,0.0
27,1970-01-01 00:00:00,Collapsible Pet Bowl,0.0
28,1970-01-01 00:00:00,Collapsible Shopping Bag,0.0
29,1970-01-01 00:00:00,Compact Selfie Stick,0.0
30,1970-01-01 00:00:00,Electronics Accessory Pouch,0.0
31,1970-01-01 00:00:00,Fashion Sunglasses & Pouch,0.0
32,1970-01-01 00:00:00,Foam Can and Bottle Cooler,0.0
33,1970-01-01 00:00:00,Google Collapsible Pet Bowl,0.0
34,1970-01-01 00:00:00,Google Kick Ball,0.0
35,1970-01-01 00:00:00,Google Laptop and Cell Phone Stickers,0.0
36,1970-01-01 00:00:00,Google Pet Feeding Mat,0.0
37,1970-01-01 00:00:00,Google Spiral Leather Journal,0.0
38,1970-01-01 00:00:00,Google Sunglasses,0.0
39,1970-01-01 00:00:00,YouTube Men's Short Sleeve Hero Tee Black,0.0
40,1970-01-01 00:00:33,Google Canvas Tote Natural/Navy,0.0
41,1970-01-01 00:01:21,Google Laptop and Cell Phone Stickers,0.0
42,1970-01-01 00:08:06,Electronics Accessory Pouch,0.0
43,1970-01-01 00:22:57,Yoga Mat,0.0
44,1970-01-01 00:24:53,Electronics Accessory Pouch,0.0
45,1970-01-01 00:27:50,Google Canvas Tote Natural/Navy,0.0
46,1970-01-01 00:28:28,Chevron Shopper,0.0
47,1970-01-01 00:28:31,Sport Bag,0.0
48,1970-01-01 00:31:16,Electronics Accessory Pouch,0.0
49,1970-01-01 00:32:42,Electronics Accessory Pouch,0.0

In [55]:
from sklearn.ensemble import IsolationForest
from sklearn.impute import SimpleImputer

# Mengisi nilai NaN dengan median
imputer = SimpleImputer(strategy='median')
df_filled = imputer.fit_transform(df[['transactions']])

# Inisialisasi model Isolation Forest
clf = IsolationForest(contamination=0.05)

# Fit dan prediksi anomali berdasarkan jumlah transaksi
df['anomaly_score'] = clf.fit_predict(df_filled)

# Analisis hasil anomali
anomalies = df[df['anomaly_score'] == -1]
print("Detected anomalies:")
print(anomalies)

anomalies.to_csv('test2.csv', index=False)

Detected anomalies:
            fullVisitorId channelGrouping                time        country  \
2014   902909418531010642          Direct 1970-01-08 17:38:46  United States
2352  1398262961791736387        Referral 1970-01-02 20:03:00  United States
2410  4002137233348878949  Organic Search 1970-01-09 22:40:59  United States
2431   112305056557684257        Referral 1970-01-02 12:02:45  United States
2585  5873491468914414978  Organic Search 1970-01-29 21:54:16      Venezuela
2662  9377429831454005466  Organic Search 1970-02-07 02:05:08  United States
3108  5712192985842423649        Referral 1970-01-04 06:45:35  United States
3380  3684045780508318181  Organic Search 1970-01-11 18:42:39      Venezuela
3626  9377429831454005466  Organic Search 1970-02-07 02:05:08  United States
5001  9415047435363681557          Direct 1970-01-11 10:16:25  United States
5430  3244885836845029978        Referral 1970-01-20 20:43:01  United States
5440   112305056557684257        Referral 1970-01-16 06:14:44  United States
5488  9894955795481014038  Organic Search 1970-01-01 09:51:13      Venezuela
5809  9894955795481014038  Organic Search 1970-02-10 06:03:16      Venezuela
5816  1599233696438848114  Organic Search 1970-01-09 06:20:02  United States
5971  1449902026609269877  Organic Search 1970-01-20 02:19:57  United States
6324  5478724114712597508        Referral 1970-01-20 21:22:48  United States
6327  3244885836845029978        Referral 1970-01-20 20:43:01  United States
6464   376544334500131710          Direct 1970-01-02 21:44:13  United States
6731   966739175376367480  Organic Search 1970-01-21 12:41:30  United States
7203  9894955795481014038  Organic Search 1970-01-01 09:51:13      Venezuela
7959  1449902026609269877  Organic Search 1970-01-20 02:19:57  United States
8225  7344519175727343086  Organic Search 1970-02-22 18:15:39      Venezuela
8583  4578640586284138624  Organic Search 1970-01-19 20:09:48  United States
8594   112305056557684257        Referral 1970-01-11 21:15:12  United States
9343  5873491468914414978  Organic Search 1970-01-30 15:13:33      Venezuela
9576  9264804092676520813  Organic Search 1970-01-02 15:50:00      Venezuela

                               city  totalTransactionRevenue  transactions  \
2014  not available in demo dataset             3.097000e+07           2.0
2352                  Mountain View             7.797000e+07           2.0
2410                  Mountain View             1.539700e+08           2.0
2431  not available in demo dataset             2.806600e+08           2.0
2585                      Maracaibo             4.708100e+08           2.0
2662  not available in demo dataset             4.198300e+08           2.0
3108                       New York             7.080300e+08           2.0
3380                      Maracaibo             3.154600e+08           2.0
3626  not available in demo dataset             4.198300e+08           2.0
5001                  San Francisco             5.598300e+08           2.0
5430  not available in demo dataset             5.945580e+09           2.0
5440  not available in demo dataset             2.806600e+08           2.0
5488                      Maracaibo             2.942000e+08           2.0
5809                      Maracaibo             2.264400e+08           2.0
5816  not available in demo dataset             1.070000e+07           2.0
5971                       New York             6.516200e+08           2.0
6324                       New York             3.295000e+07           2.0
6327  not available in demo dataset             5.945580e+09           2.0
6464                        Chicago             6.145100e+08           2.0
6731                    San Antonio             5.090000e+06           2.0
7203                      Maracaibo             2.942000e+08           2.0
7959                       New York             6.516200e+08           2.0
8225  not available in demo dataset             5.051400e+08           3.0
8583                          Salem             1.889800e+08           2.0
8594  not available in demo dataset             2.806600e+08           2.0
9343                      Maracaibo             4.708100e+08           2.0
9576  not available in demo dataset             6.239580e+09           6.0

      timeOnSite  pageviews  sessionQualityDim      date     visitId   type  \
2014      1896.0       71.0                NaN  20161005  1475681818   PAGE
2352       825.0       50.0                NaN  20160930  1475274041   PAGE
2410      4593.0       77.0                NaN  20160826  1472269236   PAGE
2431      1610.0       68.0                NaN  20160828  1472410136   PAGE
2585      3607.0      116.0                NaN  20160825  1472162809   PAGE
2662      5721.0      115.0                NaN  20160906  1473195039   PAGE
3108      3856.0      147.0                NaN  20160818  1471534308   PAGE
3380      1246.0       55.0                NaN  20160821  1471828197   PAGE
3626      5721.0      115.0                NaN  20160906  1473195039   PAGE
5001      4162.0       78.0                NaN  20160826  1472232863   PAGE
5430      2028.0       87.0                NaN  20160822  1471891823   PAGE
5440      1610.0       68.0                NaN  20160828  1472410136   PAGE
5488      7256.0      121.0                NaN  20160825  1472160087   PAGE
5809      5406.0      117.0                NaN  20160826  1472233355   PAGE
5816      2213.0       88.0                NaN  20160904  1473028458   PAGE
5971      2507.0       48.0                NaN  20160826  1472200125   PAGE
6324      2210.0       86.0                NaN  20160805  1470418863   PAGE
6327      2028.0       87.0                NaN  20160822  1471891823   PAGE
6464      1650.0       37.0                NaN  20160828  1472392033   PAGE
6731      7433.0      138.0                NaN  20160910  1473555357   PAGE
7203      7256.0      121.0                NaN  20160825  1472160087   PAGE
7959      2507.0       48.0                NaN  20160826  1472200125   PAGE
8225      5023.0      309.0                NaN  20160826  1472240181  EVENT
8583      2526.0       26.0                NaN  20160926  1474923302   PAGE
8594      1610.0       68.0                NaN  20160828  1472410136   PAGE
9343      3607.0      116.0                NaN  20160825  1472162809   PAGE
9576     12466.0      323.0                NaN  20160825  1472130683   PAGE

      productRefundAmount  productQuantity  productPrice  productRevenue  \
2014                  NaN              NaN       1990000             NaN
2352                  NaN              NaN       3990000             NaN
2410                  NaN              NaN      11190000             NaN
2431                  NaN              NaN      11190000             NaN
2585                  NaN              NaN      13990000             NaN
2662                  NaN              NaN      13990000             NaN
3108                  NaN              NaN      13990000             NaN
3380                  NaN              NaN       4990000             NaN
3626                  NaN              NaN       4990000             NaN
5001                  NaN              NaN       9990000             NaN
5430                  NaN              NaN       7990000             NaN
5440                  NaN              NaN       7990000             NaN
5488                  NaN              NaN       4990000             NaN
5809                  NaN              NaN       4990000             NaN
5816                  NaN              NaN       4990000             NaN
5971                  NaN              NaN       4990000             NaN
6324                  NaN              NaN       3990000             NaN
6327                  NaN              NaN       3990000             NaN
6464                  NaN              NaN      12790000             NaN
6731                  NaN              NaN      15990000             NaN
7203                  NaN              NaN      15990000             NaN
7959                  NaN              NaN       3500000             NaN
8225                  NaN              NaN      19990000             NaN
8583                  NaN              NaN      15990000             NaN
8594                  NaN              NaN      63990000             NaN
9343                  NaN              NaN      79990000             NaN
9576                  NaN              NaN       4990000             NaN

          productSKU                    v2ProductName  \
2014  GGOEGKAA019299     Switch Tone Color Crayon Pen
2352  GGOEGPJC203399                Crunch-It Dog Toy
2410  GGOEGBCR024399                 Google Lunch Bag
2431  GGOEGBCR024399                 Google Lunch Bag
2585  GGOEGBCR024399                 Google Lunch Bag
2662  GGOEGBCR024399                 Google Lunch Bag
3108  GGOEGBCR024399                 Google Lunch Bag
3380  GGOEGBFC018799      Electronics Accessory Pouch
3626  GGOEGBFC018799      Electronics Accessory Pouch
5001  GGOEGBJC014399                  Google Tote Bag
5430  GGOEGBJC014399                  Google Tote Bag
5440  GGOEGBJC014399                  Google Tote Bag
5488  GGOEGBJC019999         Collapsible Shopping Bag
5809  GGOEGBJC019999         Collapsible Shopping Bag
5816  GGOEGBJC019999         Collapsible Shopping Bag
5971  GGOEGBJC019999         Collapsible Shopping Bag
6324  GGOEGBJC019999       Latitudes Foldaway Shopper
6327  GGOEGBJC019999         Collapsible Shopping Bag
6464  GGOEGBJL013999  Google Canvas Tote Natural/Navy
6731  GGOEGBJL013999  Google Canvas Tote Natural/Navy
7203  GGOEGBJL013999  Google Canvas Tote Natural/Navy
7959  GGOEGBJR018199            Reusable Shopping Bag
8225  GGOEGBMB073799   Google Zipper-front Sports Bag
8583  GGOEGBMB073799   Google Zipper-front Sports Bag
8594  GGOEGBMC056599              Waterproof Gear Bag
9343  GGOEGBMC056599               Waterpoof Gear Bag
9576  GGOEGBMJ013399                        Sport Bag

              v2ProductCategory productVariant currencyCode  itemQuantity  \
2014      Home/Accessories/Fun/      (not set)          USD           NaN
2352      Home/Accessories/Pet/      (not set)          USD           NaN
2410                 Home/Bags/      (not set)          USD           NaN
2431                 Home/Bags/      (not set)          USD           NaN
2585                 Home/Bags/      (not set)          USD           NaN
2662                 Home/Bags/      (not set)          USD           NaN
3108  Home/Limited Supply/Bags/      (not set)          USD           NaN
3380                 Home/Bags/      (not set)          USD           NaN
3626                 Home/Bags/      (not set)          USD           NaN
5001                 Home/Bags/      (not set)          USD           NaN
5430                 Home/Bags/      (not set)          USD           NaN
5440                 Home/Bags/      (not set)          USD           NaN
5488                 Home/Bags/      (not set)          USD           NaN
5809                 Home/Bags/      (not set)          USD           NaN
5816                 Home/Bags/      (not set)          USD           NaN
5971                 Home/Bags/      (not set)          USD           NaN
6324  Home/Limited Supply/Bags/      (not set)          USD           NaN
6327                 Home/Bags/      (not set)          USD           NaN
6464                 Home/Bags/      (not set)          USD           NaN
6731                 Home/Bags/      (not set)          USD           NaN
7203                 Home/Bags/      (not set)          USD           NaN
7959                 Home/Bags/      (not set)          USD           NaN
8225                 Home/Bags/      (not set)          NaN           NaN
8583                 Home/Bags/      (not set)          USD           NaN
8594                 Home/Bags/      (not set)          USD           NaN
9343                 Home/Bags/      (not set)          USD           NaN
9576                 Home/Bags/      (not set)          USD           NaN

      itemRevenue  transactionRevenue  transactionId pageTitle  searchKeyword  \
2014          NaN                 NaN            NaN       Fun            NaN
2352          NaN                 NaN            NaN       Pet            NaN
2410          NaN                 NaN            NaN      Bags            NaN
2431          NaN                 NaN            NaN      Bags            NaN
2585          NaN                 NaN            NaN      Bags            NaN
2662          NaN                 NaN            NaN      Bags            NaN
3108          NaN                 NaN            NaN      Bags            NaN
3380          NaN                 NaN            NaN      Bags            NaN
3626          NaN                 NaN            NaN      Bags            NaN
5001          NaN                 NaN            NaN      Bags            NaN
5430          NaN                 NaN            NaN      Bags            NaN
5440          NaN                 NaN            NaN      Bags            NaN
5488          NaN                 NaN            NaN      Bags            NaN
5809          NaN                 NaN            NaN      Bags            NaN
5816          NaN                 NaN            NaN      Bags            NaN
5971          NaN                 NaN            NaN      Bags            NaN
6324          NaN                 NaN            NaN      Bags            NaN
6327          NaN                 NaN            NaN      Bags            NaN
6464          NaN                 NaN            NaN      Bags            NaN
6731          NaN                 NaN            NaN      Bags            NaN
7203          NaN                 NaN            NaN      Bags            NaN
7959          NaN                 NaN            NaN      Bags            NaN
8225          NaN                 NaN            NaN      Bags            NaN
8583          NaN                 NaN            NaN      Bags            NaN
8594          NaN                 NaN            NaN      Bags            NaN
9343          NaN                 NaN            NaN      Bags            NaN
9576          NaN                 NaN            NaN      Bags            NaN

         pagePathLevel1  eCommerceAction_type  eCommerceAction_step  \
2014  /google+redesign/                     0                     1
2352  /google+redesign/                     0                     1
2410  /google+redesign/                     0                     1
2431  /google+redesign/                     0                     1
2585  /google+redesign/                     0                     1
2662  /google+redesign/                     0                     1
3108  /google+redesign/                     0                     1
3380  /google+redesign/                     0                     1
3626  /google+redesign/                     0                     1
5001  /google+redesign/                     0                     1
5430  /google+redesign/                     0                     1
5440  /google+redesign/                     0                     1
5488  /google+redesign/                     0                     1
5809  /google+redesign/                     0                     1
5816  /google+redesign/                     0                     1
5971  /google+redesign/                     0                     1
6324  /google+redesign/                     0                     1
6327  /google+redesign/                     0                     1
6464  /google+redesign/                     0                     1
6731  /google+redesign/                     0                     1
7203  /google+redesign/                     0                     1
7959  /google+redesign/                     0                     1
8225  /google+redesign/                     1                     1
8583  /google+redesign/                     0                     1
8594  /google+redesign/                     0                     1
9343  /google+redesign/                     0                     1
9576  /google+redesign/                     0                     1

      eCommerceAction_option  anomaly_score
2014                     NaN             -1
2352                     NaN             -1
2410                     NaN             -1
2431                     NaN             -1
2585                     NaN             -1
2662                     NaN             -1
3108                     NaN             -1
3380                     NaN             -1
3626                     NaN             -1
5001                     NaN             -1
5430                     NaN             -1
5440                     NaN             -1
5488                     NaN             -1
5809                     NaN             -1
5816                     NaN             -1
5971                     NaN             -1
6324                     NaN             -1
6327                     NaN             -1
6464                     NaN             -1
6731                     NaN             -1
7203                     NaN             -1
7959                     NaN             -1
8225                     NaN             -1
8583                     NaN             -1
8594                     NaN             -1
9343                     NaN             -1
9576                     NaN             -1

### Detect any anomalies, such as a sharp decrease or increase in the number of transactions for a specific product.

In [129]:
# Menampilkan informasi umum tentang dataset
print("Informasi umum tentang dataset:")
print(df.info())

Informasi umum tentang dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   fullVisitorId            10000 non-null  uint64
 1   channelGrouping          10000 non-null  object
 2   time                     10000 non-null  int64
 3   country                  10000 non-null  object
 4   city                     10000 non-null  object
 5   totalTransactionRevenue  619 non-null    float64
 6   transactions             628 non-null    float64
 7   timeOnSite               9713 non-null   float64
 8   pageviews                9999 non-null   float64
 9   sessionQualityDim        19 non-null     float64
 10  date                     10000 non-null  int64
 11  visitId                  10000 non-null  int64
 12  type                     10000 non-null  object
 13  productRefundAmount      0 non-null      float64
 14  productQuantity          45 non-null     float64
 15  productPrice             10000 non-null  int64
 16  productRevenue           0 non-null      float64
 17  productSKU               10000 non-null  object
 18  v2ProductName            10000 non-null  object
 19  v2ProductCategory        10000 non-null  object
 20  productVariant           10000 non-null  object
 21  currencyCode             9614 non-null   object
 22  itemQuantity             0 non-null      float64
 23  itemRevenue              0 non-null      float64
 24  transactionRevenue       0 non-null      float64
 25  transactionId            0 non-null      float64
 26  pageTitle                9908 non-null   object
 27  searchKeyword            0 non-null      float64
 28  pagePathLevel1           10000 non-null  object
 29  eCommerceAction_type     10000 non-null  int64
 30  eCommerceAction_step     10000 non-null  int64
 31  eCommerceAction_option   0 non-null      float64
dtypes: float64(14), int64(6), object(11), uint64(1)
memory usage: 2.4+ MB
None

In [134]:
# Mendefinisikan nilai ambang batas untuk totalTransactionRevenue dan transactions
threshold_revenue = 1000000  # contoh: nilai totalTransactionRevenue tinggi
threshold_transactions = 100  # contoh: nilai transactions tinggi

# Mengecek entri dengan nilai tinggi
high_values = df[(df['totalTransactionRevenue'] > threshold_revenue) | (df['transactions'] > threshold_transactions)]
print("\nEntri dengan nilai totalTransactionRevenue atau transactions tinggi:")
print(high_values)

Kasus dengan nilai totalTransactionRevenue atau transactions null:
            fullVisitorId channelGrouping     time        country  \
0     2515546493837534633  Organic Search   966564         Taiwan
1     9361741997835388618  Organic Search   157377         France
2     7313828956068851679        Referral   228279  United States
3     6036794406403793540  Organic Search  1615618  United States
4     7847280609739507227  Organic Search    37832         Canada
...                   ...             ...      ...            ...
9995  8518740059623315737        Referral    83144  United States
9996  1592171014215970461  Organic Search   302378       Colombia
9997  6776942687101397292      Affiliates    41387         Israel
9998  3008082643543388126  Organic Search    28613         Canada
9999  4307804717807925609  Organic Search   407285  United States

                               city  totalTransactionRevenue  transactions  \
0                         (not set)                      NaN           NaN
1     not available in demo dataset                      NaN           NaN
2                     San Francisco                      NaN           NaN
3                           Boulder                      NaN           NaN
4     not available in demo dataset                      NaN           NaN
...                             ...                      ...           ...
9995                      Ann Arbor                      NaN           NaN
9996                         Bogota                      NaN           NaN
9997  not available in demo dataset                      NaN           NaN
9998                       Montreal                      NaN           NaN
9999  not available in demo dataset                      NaN           NaN

      timeOnSite  pageviews  sessionQualityDim      date     visitId  type  \
0         1567.0       82.0               17.0  20170721  1500643403  PAGE
1          321.0        8.0                NaN  20170413  1492114470  PAGE
2          927.0       11.0               63.0  20170727  1501198444  PAGE
3         1616.0       13.0               38.0  20170731  1501522359  PAGE
4         1222.0       45.0               53.0  20170728  1501300311  PAGE
...          ...        ...                ...       ...         ...   ...
9995       561.0       18.0                NaN  20160809  1470768035  PAGE
9996       365.0        7.0                NaN  20161005  1475679617  PAGE
9997       107.0        7.0                NaN  20160901  1472737682  PAGE
9998        93.0       11.0                NaN  20160929  1475183739  PAGE
9999       455.0       21.0                NaN  20160904  1473041497  PAGE

      productRefundAmount  productQuantity  productPrice  productRevenue  \
0                     NaN              NaN             0             NaN
1                     NaN              NaN             0             NaN
2                     NaN              NaN             0             NaN
3                     NaN              NaN             0             NaN
4                     NaN              NaN             0             NaN
...                   ...              ...           ...             ...
9995                  NaN              NaN       4990000             NaN
9996                  NaN              NaN       4990000             NaN
9997                  NaN              NaN       4990000             NaN
9998                  NaN              NaN       4990000             NaN
9999                  NaN              NaN       4990000             NaN

          productSKU                       v2ProductName  \
0            9180781            Suitcase Organizer Cubes
1            9180793  26 oz Double Wall Insulated Bottle
2            9180838            Metal Texture Roller Pen
3            9180838            Metal Texture Roller Pen
4            9180838            Metal Texture Roller Pen
...              ...                                 ...
9995  GGOEGBMJ013399                           Sport Bag
9996  GGOEGBMJ013399                           Sport Bag
9997  GGOEGBMJ013399                           Sport Bag
9998  GGOEGBMJ013399                           Sport Bag
9999  GGOEGBMJ013399                           Sport Bag

              v2ProductCategory productVariant currencyCode  itemQuantity  \
0                     (not set)      (not set)          USD           NaN
1                     (not set)      (not set)          USD           NaN
2                     (not set)      (not set)          USD           NaN
3                     (not set)      (not set)          USD           NaN
4                     (not set)      (not set)          USD           NaN
...                         ...            ...          ...           ...
9995  Home/Limited Supply/Bags/      (not set)          USD           NaN
9996                 Home/Bags/      (not set)          USD           NaN
9997                 Home/Bags/      (not set)          USD           NaN
9998                 Home/Bags/      (not set)          USD           NaN
9999                 Home/Bags/      (not set)          USD           NaN

      itemRevenue  transactionRevenue  transactionId pageTitle  searchKeyword  \
0             NaN                 NaN            NaN       NaN            NaN
1             NaN                 NaN            NaN       NaN            NaN
2             NaN                 NaN            NaN       NaN            NaN
3             NaN                 NaN            NaN       NaN            NaN
4             NaN                 NaN            NaN       NaN            NaN
...           ...                 ...            ...       ...            ...
9995          NaN                 NaN            NaN      Bags            NaN
9996          NaN                 NaN            NaN      Bags            NaN
9997          NaN                 NaN            NaN      Bags            NaN
9998          NaN                 NaN            NaN      Bags            NaN
9999          NaN                 NaN            NaN      Bags            NaN

         pagePathLevel1  eCommerceAction_type  eCommerceAction_step  \
0       /storeitem.html                     0                     1
1       /storeitem.html                     0                     1
2       /storeitem.html                     0                     1
3       /storeitem.html                     0                     1
4       /storeitem.html                     0                     1
...                 ...                   ...                   ...
9995  /google+redesign/                     0                     1
9996  /google+redesign/                     0                     1
9997  /google+redesign/                     0                     1
9998  /google+redesign/                     0                     1
9999  /google+redesign/                     0                     1

      eCommerceAction_option
0                        NaN
1                        NaN
2                        NaN
3                        NaN
4                        NaN
...                      ...
9995                     NaN
9996                     NaN
9997                     NaN
9998                     NaN
9999                     NaN

[9381 rows x 32 columns]

Entri dengan nilai sessionQualityDim, timeOnSite, atau pageviews rendah:
            fullVisitorId channelGrouping     time        country  \
0     2515546493837534633  Organic Search   966564         Taiwan
2     7313828956068851679        Referral   228279  United States
3     6036794406403793540  Organic Search  1615618  United States
4     7847280609739507227  Organic Search    37832         Canada
5     1371078687799372953        Referral   478901  United States
...                   ...             ...      ...            ...
9972  4866336971025453091  Organic Search    21117         Canada
9975   804795629022410643  Organic Search    26981          Italy
9984  3570683077223774672          Direct    15574  United States
9986  1054123144908181920          Social    13366   South Africa
9988  6442689868405596515          Direct     4273          Spain

                               city  totalTransactionRevenue  transactions  \
0                         (not set)                      NaN           NaN
2                     San Francisco                      NaN           NaN
3                           Boulder                      NaN           NaN
4     not available in demo dataset                      NaN           NaN
5                         Ann Arbor               67570000.0           1.0
...                             ...                      ...           ...
9972  not available in demo dataset                      NaN           NaN
9975  not available in demo dataset                      NaN           NaN
9984                       New York                      NaN           NaN
9986  not available in demo dataset                      NaN           NaN
9988  not available in demo dataset                      NaN           NaN

      timeOnSite  pageviews  sessionQualityDim      date     visitId  type  \
0         1567.0       82.0               17.0  20170721  1500643403  PAGE
2          927.0       11.0               63.0  20170727  1501198444  PAGE
3         1616.0       13.0               38.0  20170731  1501522359  PAGE
4         1222.0       45.0               53.0  20170728  1501300311  PAGE
5         1569.0       48.0               87.0  20170726  1501111386  PAGE
...          ...        ...                ...       ...         ...   ...
9972        35.0        6.0                NaN  20160803  1470268439  PAGE
9975        49.0        6.0                NaN  20160907  1473245499  PAGE
9984        16.0        2.0                NaN  20160908  1473391485  PAGE
9986        35.0        3.0                NaN  20161005  1475678729  PAGE
9988         4.0        2.0                NaN  20160824  1472044349  PAGE

      productRefundAmount  productQuantity  productPrice  productRevenue  \
0                     NaN              NaN             0             NaN
2                     NaN              NaN             0             NaN
3                     NaN              NaN             0             NaN
4                     NaN              NaN             0             NaN
5                     NaN              NaN             0             NaN
...                   ...              ...           ...             ...
9972                  NaN              NaN       4990000             NaN
9975                  NaN              NaN       4990000             NaN
9984                  NaN              NaN       4990000             NaN
9986                  NaN              NaN       4990000             NaN
9988                  NaN              NaN       4990000             NaN

          productSKU             v2ProductName          v2ProductCategory  \
0            9180781  Suitcase Organizer Cubes                  (not set)
2            9180838  Metal Texture Roller Pen                  (not set)
3            9180838  Metal Texture Roller Pen                  (not set)
4            9180838  Metal Texture Roller Pen                  (not set)
5            9180838  Metal Texture Roller Pen                  (not set)
...              ...                       ...                        ...
9972  GGOEGBMJ013399                 Sport Bag  Home/Limited Supply/Bags/
9975  GGOEGBMJ013399                 Sport Bag                 Home/Bags/
9984  GGOEGBMJ013399                 Sport Bag                 Home/Bags/
9986  GGOEGBMJ013399                 Sport Bag                 Home/Bags/
9988  GGOEGBMJ013399                 Sport Bag                 Home/Bags/

     productVariant currencyCode  itemQuantity  itemRevenue  \
0         (not set)          USD           NaN          NaN
2         (not set)          USD           NaN          NaN
3         (not set)          USD           NaN          NaN
4         (not set)          USD           NaN          NaN
5         (not set)          USD           NaN          NaN
...             ...          ...           ...          ...
9972      (not set)          USD           NaN          NaN
9975      (not set)          USD           NaN          NaN
9984      (not set)          USD           NaN          NaN
9986      (not set)          USD           NaN          NaN
9988      (not set)          USD           NaN          NaN

      transactionRevenue  transactionId pageTitle  searchKeyword  \
0                    NaN            NaN       NaN            NaN
2                    NaN            NaN       NaN            NaN
3                    NaN            NaN       NaN            NaN
4                    NaN            NaN       NaN            NaN
5                    NaN            NaN       NaN            NaN
...                  ...            ...       ...            ...
9972                 NaN            NaN      Bags            NaN
9975                 NaN            NaN      Bags            NaN
9984                 NaN            NaN      Bags            NaN
9986                 NaN            NaN      Bags            NaN
9988                 NaN            NaN      Bags            NaN

         pagePathLevel1  eCommerceAction_type  eCommerceAction_step  \
0       /storeitem.html                     0                     1
2       /storeitem.html                     0                     1
3       /storeitem.html                     0                     1
4       /storeitem.html                     0                     1
5       /storeitem.html                     0                     1
...                 ...                   ...                   ...
9972  /google+redesign/                     0                     1
9975  /google+redesign/                     0                     1
9984  /google+redesign/                     0                     1
9986  /google+redesign/                     0                     1
9988  /google+redesign/                     0                     1

      eCommerceAction_option
0                        NaN
2                        NaN
3                        NaN
4                        NaN
5                        NaN
...                      ...
9972                     NaN
9975                     NaN
9984                     NaN
9986                     NaN
9988                     NaN

[1161 rows x 32 columns]

Entri dengan nilai totalTransactionRevenue atau transactions tinggi:
            fullVisitorId channelGrouping     time        country  \
5     1371078687799372953        Referral   478901  United States
6     8781227467221587011        Referral   119567  United States
21    5024679608681889824  Organic Search  3155627  United States
32    7382833428985431536        Referral   812138  United States
48    7199611745811583535        Referral    95056  United States
...                   ...             ...      ...            ...
9879  4825534357105727679        Referral    17118  United States
9925  7166253532069552655         Display   279254  United States
9938  5262771322194198136        Referral     5581  United States
9958  4835031132385744572          Direct  1259955  United States
9968  2518447979646501002  Organic Search   121173  United States

               city  totalTransactionRevenue  transactions  timeOnSite  \
5         Ann Arbor               67570000.0           1.0      1569.0
6     Mountain View               24710000.0           1.0      1007.0
21          Houston              123390000.0           1.0      3899.0
32          Chicago              122390000.0           1.0      1296.0
48          Boulder              467600000.0           1.0       710.0
...             ...                      ...           ...         ...
9879  Mountain View              125100000.0           1.0       356.0
9925  San Francisco              451700000.0           1.0      1187.0
9938         Austin              150340000.0           1.0      1731.0
9958      Palo Alto               62870000.0           1.0      1643.0
9968       New York               78150000.0           1.0       705.0

      pageviews  sessionQualityDim      date     visitId  type  \
5          48.0               87.0  20170726  1501111386  PAGE
6          35.0               71.0  20170727  1501203918  PAGE
21         54.0               80.0  20170715  1500148319  PAGE
32         31.0                NaN  20170416  1492363119  PAGE
48         27.0                NaN  20170104  1483554305  PAGE
...         ...                ...       ...         ...   ...
9879       14.0                NaN  20160809  1470762213  PAGE
9925       41.0                NaN  20160818  1471550764  PAGE
9938       61.0                NaN  20160822  1471906107  PAGE
9958       32.0                NaN  20160805  1470409970  PAGE
9968       40.0                NaN  20160820  1471740007  PAGE

      productRefundAmount  productQuantity  productPrice  productRevenue  \
5                     NaN              NaN             0             NaN
6                     NaN              NaN             0             NaN
21                    NaN              NaN             0             NaN
32                    NaN              NaN             0             NaN
48                    NaN              NaN             0             NaN
...                   ...              ...           ...             ...
9879                  NaN              NaN       4990000             NaN
9925                  NaN              NaN       4990000             NaN
9938                  NaN              NaN       4990000             NaN
9958                  NaN              NaN       4990000             NaN
9968                  NaN              NaN       4990000             NaN

          productSKU                                      v2ProductName  \
5            9180838                           Metal Texture Roller Pen
6            9180838                           Metal Texture Roller Pen
21           9182569                           Google Men's  Zip Hoodie
32           9182721  Google Men's 100% Cotton Short Sleeve Hero Tee...
48           9182761                   Google Women's Yoga Jacket Black
...              ...                                                ...
9879  GGOEGBMJ013399                                          Sport Bag
9925  GGOEGBMJ013399                                          Sport Bag
9938  GGOEGBMJ013399                                          Sport Bag
9958  GGOEGBMJ013399                                          Sport Bag
9968  GGOEGBMJ013399                                          Sport Bag

              v2ProductCategory productVariant currencyCode  itemQuantity  \
5                     (not set)      (not set)          USD           NaN
6                     (not set)      (not set)          USD           NaN
21                    (not set)      (not set)          USD           NaN
32                    (not set)      (not set)          USD           NaN
48                    (not set)      (not set)          USD           NaN
...                         ...            ...          ...           ...
9879  Home/Limited Supply/Bags/      (not set)          USD           NaN
9925  Home/Limited Supply/Bags/      (not set)          USD           NaN
9938                 Home/Bags/      (not set)          USD           NaN
9958  Home/Limited Supply/Bags/      (not set)          NaN           NaN
9968                 Home/Bags/      (not set)          USD           NaN

      itemRevenue  transactionRevenue  transactionId pageTitle  searchKeyword  \
5             NaN                 NaN            NaN       NaN            NaN
6             NaN                 NaN            NaN       NaN            NaN
21            NaN                 NaN            NaN       NaN            NaN
32            NaN                 NaN            NaN       NaN            NaN

In [136]:
threshold_time = 60 # contoh: nilai waktu rendah
threshold_pageviews = 3 # contoh: nilai pageviews rendah

# Mengecek entri dengan nilai rendah
low_values = df[(df['sessionQualityDim'] < 100) | (df['timeOnSite'] < threshold_time) | (df['pageviews'] < threshold_pageviews)]
print("\nEntri dengan nilai sessionQualityDim, timeOnSite, atau pageviews rendah:")
display(low_values.head())

Entri dengan nilai sessionQualityDim, timeOnSite, atau pageviews rendah:

,fullVisitorId,channelGrouping,time,country,city,totalTransactionRevenue,transactions,timeOnSite,pageviews,sessionQualityDim,date,visitId,type,productRefundAmount,productQuantity,productPrice,productRevenue,productSKU,v2ProductName,v2ProductCategory,productVariant,currencyCode,itemQuantity,itemRevenue,transactionRevenue,transactionId,pageTitle,searchKeyword,pagePathLevel1,eCommerceAction_type,eCommerceAction_step,eCommerceAction_option
0,2515546493837534633,Organic Search,966564,Taiwan,(not set),NaN,NaN,1567.0,82.0,17.0,20170721,1500643403,PAGE,NaN,NaN,0,NaN,9180781,Suitcase Organizer Cubes,(not set),(not set),USD,NaN,NaN,NaN,NaN,NaN,NaN,/storeitem.html,0,1,NaN
2,7313828956068851679,Referral,228279,United States,San Francisco,NaN,NaN,927.0,11.0,63.0,20170727,1501198444,PAGE,NaN,NaN,0,NaN,9180838,Metal Texture Roller Pen,(not set),(not set),USD,NaN,NaN,NaN,NaN,NaN,NaN,/storeitem.html,0,1,NaN
3,6036794406403793540,Organic Search,1615618,United States,Boulder,NaN,NaN,1616.0,13.0,38.0,20170731,1501522359,PAGE,NaN,NaN,0,NaN,9180838,Metal Texture Roller Pen,(not set),(not set),USD,NaN,NaN,NaN,NaN,NaN,NaN,/storeitem.html,0,1,NaN
4,7847280609739507227,Organic Search,37832,Canada,not available in demo dataset,NaN,NaN,1222.0,45.0,53.0,20170728,1501300311,PAGE,NaN,NaN,0,NaN,9180838,Metal Texture Roller Pen,(not set),(not set),USD,NaN,NaN,NaN,NaN,NaN,NaN,/storeitem.html,0,1,NaN
5,1371078687799372953,Referral,478901,United States,Ann Arbor,67570000.0,1.0,1569.0,48.0,87.0,20170726,1501111386,PAGE,NaN,NaN,0,NaN,9180838,Metal Texture Roller Pen,(not set),(not set),USD,NaN,NaN,NaN,NaN,NaN,NaN,/storeitem.html,0,1,NaN

In [150]:
# Menampilkan kolom yang harus ditampilkan
columns_to_display = ['currencyCode', 'totalTransactionRevenue', 'transactions']

# Menampilkan data dengan mata uang selain USD 
currency_consistency_display = currency_consistency[(currency_consistency['currencyCode'] != 'USD')][columns_to_display]
print("\nEntri dengan mata uang selain USD dan nilai yang tidak null:")
display(currency_consistency_display.head())

Entri dengan mata uang selain USD dan nilai yang tidak null:

    currencyCode  totalTransactionRevenue  transactions
92           NaN                      NaN           NaN
100          NaN              181610000.0           1.0
106          NaN               39990000.0           1.0
114          NaN                      NaN           NaN
117          NaN                      NaN           NaN

In [122]:
# 1. Mengecek TotalTransactionRevenue dan Transactions
missing_values = df[df['totalTransactionRevenue'].isnull() | df['transactions'].isnull()]

# Menampilkan hasil
print("Missing values in TotalTransactionRevenue and Transactions:")
display(missing_values.head())

Missing values in TotalTransactionRevenue and Transactions:

,fullVisitorId,channelGrouping,time,country,city,totalTransactionRevenue,transactions,timeOnSite,pageviews,sessionQualityDim,date,visitId,type,productRefundAmount,productQuantity,productPrice,productRevenue,productSKU,v2ProductName,v2ProductCategory,productVariant,currencyCode,itemQuantity,itemRevenue,transactionRevenue,transactionId,pageTitle,searchKeyword,pagePathLevel1,eCommerceAction_type,eCommerceAction_step,eCommerceAction_option
0,2515546493837534633,Organic Search,966564,Taiwan,(not set),NaN,NaN,1567.0,82.0,17.0,20170721,1500643403,PAGE,NaN,NaN,0,NaN,9180781,Suitcase Organizer Cubes,(not set),(not set),USD,NaN,NaN,NaN,NaN,NaN,NaN,/storeitem.html,0,1,NaN
1,9361741997835388618,Organic Search,157377,France,not available in demo dataset,NaN,NaN,321.0,8.0,NaN,20170413,1492114470,PAGE,NaN,NaN,0,NaN,9180793,26 oz Double Wall Insulated Bottle,(not set),(not set),USD,NaN,NaN,NaN,NaN,NaN,NaN,/storeitem.html,0,1,NaN
2,7313828956068851679,Referral,228279,United States,San Francisco,NaN,NaN,927.0,11.0,63.0,20170727,1501198444,PAGE,NaN,NaN,0,NaN,9180838,Metal Texture Roller Pen,(not set),(not set),USD,NaN,NaN,NaN,NaN,NaN,NaN,/storeitem.html,0,1,NaN
3,6036794406403793540,Organic Search,1615618,United States,Boulder,NaN,NaN,1616.0,13.0,38.0,20170731,1501522359,PAGE,NaN,NaN,0,NaN,9180838,Metal Texture Roller Pen,(not set),(not set),USD,NaN,NaN,NaN,NaN,NaN,NaN,/storeitem.html,0,1,NaN
4,7847280609739507227,Organic Search,37832,Canada,not available in demo dataset,NaN,NaN,1222.0,45.0,53.0,20170728,1501300311,PAGE,NaN,NaN,0,NaN,9180838,Metal Texture Roller Pen,(not set),(not set),USD,NaN,NaN,NaN,NaN,NaN,NaN,/storeitem.html,0,1,NaN

In [107]:
# Memilih baris dengan informasi lokasi yang hilang atau tidak lengkap
missing_location = df[(df['country'].isnull() | (df['country'] == '(not set)')) | 
                      (df['city'].isnull() | (df['city'] == 'not available in demo dataset'))]

# Menampilkan hanya kolom 'country' dan 'city'
print("\nMissing or incomplete location information:")

# Menampilkan lima baris pertama dari DataFrame yang telah dipilih
display(missing_location[['country', 'city']].head())

Missing or incomplete location information:

         country                           city
1         France  not available in demo dataset
4         Canada  not available in demo dataset
7          India  not available in demo dataset
8  United States  not available in demo dataset
9    New Zealand  not available in demo dataset

In [106]:
# Mengecek ChannelGrouping
channel_grouping_counts = df['channelGrouping'].value_counts().reset_index()
channel_grouping_counts.columns = ['ChannelGrouping', 'Count']

print("\nChannelGrouping counts:")
display(channel_grouping_counts)

ChannelGrouping counts:

  ChannelGrouping  Count
0  Organic Search   4539
1        Referral   2600
2          Direct   1872
3          Social    324
4     Paid Search    317
5      Affiliates    216
6         Display    131
7         (Other)      1

In [110]:
 # 4. Mengecek Waktu
min_date = df['date'].min()
max_date = df['date'].max()

print("\nDate Range - Min Date:", min_date, " Max Date:", max_date)

Date Range - Min Date: 20160801  Max Date: 20170801

In [112]:
# 5. Mengecek Produk
missing_product_info = df[df['v2ProductName'].isnull() | data['v2ProductCategory'].isnull()]

print("\nMissing product information:")
display(missing_product_info.head())

Missing product information:

Empty DataFrame
Columns: [fullVisitorId, channelGrouping, time, country, city, totalTransactionRevenue, transactions, timeOnSite, pageviews, sessionQualityDim, date, visitId, type, productRefundAmount, productQuantity, productPrice, productRevenue, productSKU, v2ProductName, v2ProductCategory, productVariant, currencyCode, itemQuantity, itemRevenue, transactionRevenue, transactionId, pageTitle, searchKeyword, pagePathLevel1, eCommerceAction_type, eCommerceAction_step, eCommerceAction_option]
Index: []

In [126]:
# # 6. Mengecek ECommerceAction_type
ecommerce_action_counts_df = ecommerce_action_counts.to_frame().reset_index()
ecommerce_action_counts_df.columns = ['ECommerceAction_type', 'Count']

print("\nECommerceAction_type counts:")
display(ecommerce_action_counts_df.head())

ECommerceAction_type counts:

   ECommerceAction_type  Count
0                     0   9568
1                     1    195
2                     2    191
3                     3     46

In [119]:
# 7. Mengecek Revenue dan Transaksi
high_revenue_single_transaction = df[(df['transactions'] > 0) & (df['totalTransactionRevenue'] > 1000)]

print("\nTransactions with high revenue but single transaction:")
display(high_revenue_single_transaction.head())

Transactions with high revenue but single transaction:

,fullVisitorId,channelGrouping,time,country,city,totalTransactionRevenue,transactions,timeOnSite,pageviews,sessionQualityDim,date,visitId,type,productRefundAmount,productQuantity,productPrice,productRevenue,productSKU,v2ProductName,v2ProductCategory,productVariant,currencyCode,itemQuantity,itemRevenue,transactionRevenue,transactionId,pageTitle,searchKeyword,pagePathLevel1,eCommerceAction_type,eCommerceAction_step,eCommerceAction_option
5,1371078687799372953,Referral,1970-01-01 00:00:00.000478901,United States,Ann Arbor,67570000.0,1.0,1569.0,48.0,87.0,20170726,1501111386,PAGE,NaN,NaN,0,NaN,9180838,Metal Texture Roller Pen,(not set),(not set),USD,NaN,NaN,NaN,NaN,NaN,NaN,/storeitem.html,0,1,NaN
6,8781227467221587011,Referral,1970-01-01 00:00:00.000119567,United States,Mountain View,24710000.0,1.0,1007.0,35.0,71.0,20170727,1501203918,PAGE,NaN,NaN,0,NaN,9180838,Metal Texture Roller Pen,(not set),(not set),USD,NaN,NaN,NaN,NaN,NaN,NaN,/storeitem.html,0,1,NaN
21,5024679608681889824,Organic Search,1970-01-01 00:00:00.003155627,United States,Houston,123390000.0,1.0,3899.0,54.0,80.0,20170715,1500148319,PAGE,NaN,NaN,0,NaN,9182569,Google Men's Zip Hoodie,(not set),(not set),USD,NaN,NaN,NaN,NaN,NaN,NaN,/storeitem.html,0,1,NaN
32,7382833428985431536,Referral,1970-01-01 00:00:00.000812138,United States,Chicago,122390000.0,1.0,1296.0,31.0,NaN,20170416,1492363119,PAGE,NaN,NaN,0,NaN,9182721,Google Men's 100% Cotton Short Sleeve Hero Tee...,(not set),(not set),USD,NaN,NaN,NaN,NaN,NaN,NaN,/storeitem.html,0,1,NaN
48,7199611745811583535,Referral,1970-01-01 00:00:00.000095056,United States,Boulder,467600000.0,1.0,710.0,27.0,NaN,20170104,1483554305,PAGE,NaN,NaN,0,NaN,9182761,Google Women's Yoga Jacket Black,(not set),(not set),USD,NaN,NaN,NaN,NaN,NaN,NaN,/storeitem.html,0,1,NaN

In [121]:
# 8. Mengecek Duplikasi Data
duplicate_entries = df[df.duplicated()]

print("\nDuplicate entries:")
display(duplicate_entries.head())

Duplicate entries:

Empty DataFrame
Columns: [fullVisitorId, channelGrouping, time, country, city, totalTransactionRevenue, transactions, timeOnSite, pageviews, sessionQualityDim, date, visitId, type, productRefundAmount, productQuantity, productPrice, productRevenue, productSKU, v2ProductName, v2ProductCategory, productVariant, currencyCode, itemQuantity, itemRevenue, transactionRevenue, transactionId, pageTitle, searchKeyword, pagePathLevel1, eCommerceAction_type, eCommerceAction_step, eCommerceAction_option]
Index: []

In [154]:
from scipy.stats import zscore

# Pilih kolom yang berisi informasi produk dan jumlah transaksi
produk_kolom = 'v2ProductName'  # Ganti dengan nama kolom produk yang sesuai
transaksi_kolom = 'transactions'  # Ganti dengan nama kolom jumlah transaksi yang sesuai

# Menghitung z-score untuk deteksi anomali
df['z_score'] = zscore(df[transaksi_kolom])

# Menetapkan batas ambang z-score untuk mendeteksi anomali
batas_ambang = 2.5  # Sesuaikan sesuai dengan kebutuhan Anda

# Mendeteksi anomali berdasarkan z-score
anomali = df[abs(df['z_score']) > batas_ambang]

# Menampilkan hasil deteksi anomali
print("Deteksi Anomali:")
print(anomali[[produk_kolom, transaksi_kolom, 'z_score']])

Deteksi Anomali:
Empty DataFrame
Columns: [v2ProductName, totalTransactionRevenue, z_score]
Index: []

### Identify the most profitable city or province based on the total transaction revenue.

In [165]:
import pandas as pd

# Group the data by city
data_per_city = df[df['city'] != '(not set)'].groupby('city')

# Create an empty list to store DataFrame objects for each city
city_data_frames = []

# Populate the list with data for each city
for city, city_data_group in data_per_city:
    total_revenue = city_data_group['totalTransactionRevenue'].sum()
    total_transactions = city_data_group['transactions'].sum()
    city_data_frames.append(pd.DataFrame({'City': [city] }))

# Concatenate all city DataFrames into one DataFrame
city_data = pd.concat(city_data_frames, ignore_index=True)

# Display the city data as a table
display(city_data.head())

         City
0   Abu Dhabi
1   Ahmedabad
2  Alba Iulia
3  Alexandria
4   Amsterdam

In [168]:
# Group the data by city or province and calculate the total transaction revenue
revenue_by_city = df.groupby('city')['totalTransactionRevenue'].sum().reset_index()

# Alternatively, if you have province information instead of city
# revenue_by_province = df.groupby('province')['transaction_revenue'].sum().reset_index()

# Find the city or province with the highest total transaction revenue
most_profitable_city = revenue_by_city.loc[revenue_by_city['totalTransactionRevenue'].idxmax()]

# Alternatively, if you have province information instead of city
# most_profitable_province = revenue_by_province.loc[revenue_by_province['transaction_revenue'].idxmax()]

print("Most profitable city: ", most_profitable_city['city'])
print("Total transaction revenue: ", most_profitable_city['totalTransactionRevenue'])

Most profitable city:  not available in demo dataset
Total transaction revenue:  65102440000.0